# 配置完文件说明
# 1. 通过__type__字段来区分不同类别所对应的功能：
#      class 对应 目标分类的类别，唯一，如果后面又有类别为class的部分，则会覆盖前面的
#      single 对应 单选类属性，即：这些属性互相之间不会同时发生，某一时刻仅可存在一种
#      bool 对应 是非问题类属性，如：对于关系属性来说，仅存在发生与未发生两种状态
#      free 对应 自由创建属性，该属性不限定内容，用户可以随时在程序中创建新的，通常用于视频语义标注
#    注意：这个字段如果为空，则默认为"single"类型
# 2. 标签均采用---> <标签名: 标签索引> 的方式来表示
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
classes:
  __type__: "class"
  __objects__: 1
  猎豹: 0
  猴子: 1
  树枝: 2
  树干: 3
  草地: 4
  狮子: 5
  大象: 6
  松鼠: 7
  蝴蝶: 8
  花: 9
actions:
  __type__: "single"
  __objects__: 1
  run: 1
  jump: 2
  climb: 3
  sit: 4
  drop: 5
directions:
  __type__: "single"
  __objects__: 1
  正上: 0
  右上: 1
  正右: 2
  右下: 3
  正下: 4
  左下: 5
  正左: 6
  左上: 7
relations:
  __type__: "single"
  __objects__: 2
  "on": 1
  over: 2
  left: 3
  occlusion: 4
  touch: 5
  attack: 6
captions:
  __type__: "free"
  __objects__: 0